name = "PaalonJSON"
uuid = "93169e74-b428-45ac-8c94-b8714ebe5275"
authors = ["Koki Fushimi <paalon1936@gmail.com>"]
version = "0.1.1"

[compat]
julia = "^1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
